frases = ['¿Puedo pagar la reserva del coche de alquiler con mi tarjeta de débito?',
'¿Es necesario que pague mi reserva con una tarjeta de crédito?',
'¿Permiten el pago con tarjetas de débito?',
'¿Puedo pagar en efectivo cuando vaya a recoger mi coche?',
'¿Puedo pagar con una tarjeta de crédito que no sea nominativa?',
'¿Me pueden pedir más de una tarjeta de crédito para alquilar un coche de categoría superior?',
'La persona que conduce, ¿Tiene que ser el titular de la tarjeta de crédito?',
'¿Qué es lo que me cubre el seguro básico?',
'¿Tengo algún seguro al alquiler un coche a través de Pepecar?',
'¿Puedo contratar un seguro extra para el coche?',
'¿Es necesario algún seguro adicional?',
'Quiero que mi coche tenga cobertura de neumáticos y lunas, ¿Cómo aseguro que así sea?',
'Necesito una sillita de bebé ¿Dónde puedo alquilar una?',
'¿Puede conducir alguien por mí?',
'¿Puedo viajar entre países con un coche de alquiler?.',
'¿Tengo que pagar un extra por tasa aeroportuaria?',
'¿Puedo moverme entre islas con un coche alquiler?',
'¿Puedo contratar el servicio de wifi como un extra junto al coche?',
'¿Puedo cruzar la frontera con un coche de alquiler?',
'¿Existe alguna tasa si el coche lo recojo en el aeropuerto?',
'El impuesto de aeropuerto, ¿es un pago aparte o ya viene incluido en el total?',
'¿Qué significa “Política de combustible”?',
'¿Puedo elegir el coche que yo quiera?',
'¿Puedo alquilar un coche de lujo?',
'¿Es posible elegir el color del coche al realizar la reserva?',
'¿Puedo seleccionar el modelo de coche que yo quiera?',
'¿Qué es eso de la franquicia?',
'¿Es obligatorio depositar una fianza?',
'¿Solo puedo depositar la fianza del vehículo con una tarjeta de crédito?',
'¿Tengo que pagar un depósito?',
'¿Todos los proveedores cobran la misma fianza?',
'¿Puedo modificar mi reserva?',
'¿Es necesario que esté registrado para realizar una reserva?',
'No recibo mi email de confirmación ¿Qué puedo hacer?',
'¿Con cuánto tiempo de antelación puedo cancelar una reserva?',
'¿Qué sucede si cancelo mi reserva el mismo día?',
'¿Puedo entregar el coche en un lugar distinto de donde lo recogí?',
'Me equivoqué con algunos datos al hacer la reserva, ¿Qué puedo hacer?',
]
