
pokemons = [
    bulbasaur= {'nombre': 'Bulbasaur', 'ataque': 49', 'defensa': 49', 'vida': 45}
    ivysaur= {'nombre': 'Ivysaur', 'ataque': 62', 'defensa': 63', 'vida': 60}
    venusaur= {'nombre': 'Venusaur', 'ataque': 82', 'defensa': 83', 'vida': 80}
    mega-venusaur= {'nombre': 'Mega-Venusaur', 'ataque': 100', 'defensa': 123', 'vida': 80}
    charmander= {'nombre': 'Charmander', 'ataque': 52', 'defensa': 43', 'vida': 39}
    charmeleon= {'nombre': 'Charmeleon', 'ataque': 64', 'defensa': 58', 'vida': 58}
    charizard= {'nombre': 'Charizard', 'ataque': 84', 'defensa': 78', 'vida': 78}
    mega-charizard x= {'nombre': 'Mega-Charizard X', 'ataque': 130', 'defensa': 111', 'vida': 78}
    mega-charizard y= {'nombre': 'Mega-Charizard Y', 'ataque': 104', 'defensa': 78', 'vida': 78}
    squirtle= {'nombre': 'Squirtle', 'ataque': 48', 'defensa': 65', 'vida': 44}
    wartortle= {'nombre': 'Wartortle', 'ataque': 63', 'defensa': 80', 'vida': 59}
    blastoise= {'nombre': 'Blastoise', 'ataque': 83', 'defensa': 100', 'vida': 79}
    mega-blastoise= {'nombre': 'Mega-Blastoise', 'ataque': 103', 'defensa': 120', 'vida': 79}
    caterpie= {'nombre': 'Caterpie', 'ataque': 30', 'defensa': 35', 'vida': 45}
    metapod= {'nombre': 'Metapod', 'ataque': 20', 'defensa': 55', 'vida': 50}
    butterfree= {'nombre': 'Butterfree', 'ataque': 45', 'defensa': 50', 'vida': 60}
    weedle= {'nombre': 'Weedle', 'ataque': 35', 'defensa': 30', 'vida': 40}
    kakuna= {'nombre': 'Kakuna', 'ataque': 25', 'defensa': 50', 'vida': 45}
    beedrill= {'nombre': 'Beedrill', 'ataque': 901', 'defensa': 40', 'vida': 65}
    mega-beedrill= {'nombre': 'Mega-Beedrill', 'ataque': 150', 'defensa': 40', 'vida': 65}
    pidgey= {'nombre': 'Pidgey', 'ataque': 45', 'defensa': 40', 'vida': 40}
    pidgeotto= {'nombre': 'Pidgeotto', 'ataque': 60', 'defensa': 55', 'vida': 63}
    pidgeot= {'nombre': 'Pidgeot', 'ataque': 80', 'defensa': 75', 'vida': 83}
    mega-pidgeot= {'nombre': 'Mega-Pidgeot', 'ataque': 80', 'defensa': 80', 'vida': 83}
    rattata= {'nombre': 'Rattata', 'ataque': 56', 'defensa': 35', 'vida': 30}
    rattata de alola= {'nombre': 'Rattata de Alola', 'ataque': 56', 'defensa': 35', 'vida': 30}
    raticate= {'nombre': 'Raticate', 'ataque': 81', 'defensa': 60', 'vida': 55}
    raticate de alola= {'nombre': 'Raticate de Alola', 'ataque': 71', 'defensa': 70', 'vida': 75}
    spearow= {'nombre': 'Spearow', 'ataque': 60', 'defensa': 30', 'vida': 40}
    fearow= {'nombre': 'Fearow', 'ataque': 90', 'defensa': 65', 'vida': 65}
    ekans= {'nombre': 'Ekans', 'ataque': 60', 'defensa': 44', 'vida': 35}
    arbok= {'nombre': 'Arbok', 'ataque': 953', 'defensa': 69', 'vida': 60}
    pikachu= {'nombre': 'Pikachu', 'ataque': 55', 'defensa': 404', 'vida': 35}
    raichu= {'nombre': 'Raichu', 'ataque': 90', 'defensa': 55', 'vida': 60}
    raichu de alola= {'nombre': 'Raichu de Alola', 'ataque': 85', 'defensa': 50', 'vida': 60}
    sandshrew= {'nombre': 'Sandshrew', 'ataque': 75', 'defensa': 85', 'vida': 50}
    sandshrew de alola= {'nombre': 'Sandshrew de Alola', 'ataque': 75', 'defensa': 90', 'vida': 50}
    sandslash= {'nombre': 'Sandslash', 'ataque': 100', 'defensa': 110', 'vida': 75}
    sandslash de alola= {'nombre': 'Sandslash de Alola', 'ataque': 100', 'defensa': 120', 'vida': 75}
    nidoran♀= {'nombre': 'Nidoran♀', 'ataque': 47', 'defensa': 52', 'vida': 55}
    nidorina= {'nombre': 'Nidorina', 'ataque': 62', 'defensa': 67', 'vida': 70}
    nidoqueen= {'nombre': 'Nidoqueen', 'ataque': 927', 'defensa': 87', 'vida': 90}
    nidoran♂= {'nombre': 'Nidoran♂', 'ataque': 57', 'defensa': 40', 'vida': 46}
    nidorino= {'nombre': 'Nidorino', 'ataque': 72', 'defensa': 57', 'vida': 61}
    nidoking= {'nombre': 'Nidoking', 'ataque': 1028', 'defensa': 77', 'vida': 81}
    clefairy= {'nombre': 'Clefairy', 'ataque': 45', 'defensa': 48', 'vida': 70}
    clefable= {'nombre': 'Clefable', 'ataque': 70', 'defensa': 73', 'vida': 95}
    vulpix= {'nombre': 'Vulpix', 'ataque': 41', 'defensa': 40', 'vida': 38}
    vulpix de alola= {'nombre': 'Vulpix de Alola', 'ataque': 41', 'defensa': 40', 'vida': 38}
    ninetales= {'nombre': 'Ninetales', 'ataque': 76', 'defensa': 75', 'vida': 73}
    ninetales de alola= {'nombre': 'Ninetales de Alola', 'ataque': 67', 'defensa': 75', 'vida': 73}
    jigglypuff= {'nombre': 'Jigglypuff', 'ataque': 45', 'defensa': 20', 'vida': 115}
    wigglytuff= {'nombre': 'Wigglytuff', 'ataque': 70', 'defensa': 45', 'vida': 140}
    zubat= {'nombre': 'Zubat', 'ataque': 45', 'defensa': 35', 'vida': 40}
    golbat= {'nombre': 'Golbat', 'ataque': 80', 'defensa': 70', 'vida': 75}
    oddish= {'nombre': 'Oddish', 'ataque': 50', 'defensa': 55', 'vida': 45}
    gloom= {'nombre': 'Gloom', 'ataque': 65', 'defensa': 70', 'vida': 60}
    vileplume= {'nombre': 'Vileplume', 'ataque': 80', 'defensa': 85', 'vida': 75}
    paras= {'nombre': 'Paras', 'ataque': 70', 'defensa': 55', 'vida': 35}
    parasect= {'nombre': 'Parasect', 'ataque': 95', 'defensa': 80', 'vida': 60}
    venonat= {'nombre': 'Venonat', 'ataque': 55', 'defensa': 50', 'vida': 60}
    venomoth= {'nombre': 'Venomoth', 'ataque': 65', 'defensa': 60', 'vida': 70}
    diglett= {'nombre': 'Diglett', 'ataque': 55', 'defensa': 25', 'vida': 10}
    diglett de alola= {'nombre': 'Diglett de Alola', 'ataque': 55', 'defensa': 30', 'vida': 10}
    dugtrio= {'nombre': 'Dugtrio', 'ataque': 10011', 'defensa': 50', 'vida': 35}
    dugtrio de alola= {'nombre': 'Dugtrio de Alola', 'ataque': 100', 'defensa': 60', 'vida': 35}
    meowth= {'nombre': 'Meowth', 'ataque': 45', 'defensa': 35', 'vida': 40}
    meowth de alola= {'nombre': 'Meowth de Alola', 'ataque': 35', 'defensa': 35', 'vida': 40}
    persian= {'nombre': 'Persian', 'ataque': 70', 'defensa': 60', 'vida': 65}
    persian de alola= {'nombre': 'Persian de Alola', 'ataque': 60', 'defensa': 60', 'vida': 65}
    psyduck= {'nombre': 'Psyduck', 'ataque': 52', 'defensa': 48', 'vida': 50}
    golduck= {'nombre': 'Golduck', 'ataque': 82', 'defensa': 78', 'vida': 80}
    mankey= {'nombre': 'Mankey', 'ataque': 80', 'defensa': 35', 'vida': 40}
    primeape= {'nombre': 'Primeape', 'ataque': 105', 'defensa': 60', 'vida': 65}
    growlithe= {'nombre': 'Growlithe', 'ataque': 70', 'defensa': 45', 'vida': 55}
    arcanine= {'nombre': 'Arcanine', 'ataque': 110', 'defensa': 80', 'vida': 90}
    poliwag= {'nombre': 'Poliwag', 'ataque': 50', 'defensa': 40', 'vida': 40}
    poliwhirl= {'nombre': 'Poliwhirl', 'ataque': 65', 'defensa': 65', 'vida': 65}
    poliwrath= {'nombre': 'Poliwrath', 'ataque': 959', 'defensa': 95', 'vida': 90}
    abra= {'nombre': 'Abra', 'ataque': 20', 'defensa': 15', 'vida': 25}
    kadabra= {'nombre': 'Kadabra', 'ataque': 35', 'defensa': 30', 'vida': 40}
    alakazam= {'nombre': 'Alakazam', 'ataque': 50', 'defensa': 45', 'vida': 55}
    mega-alakazam= {'nombre': 'Mega-Alakazam', 'ataque': 50', 'defensa': 65', 'vida': 55}
    machop= {'nombre': 'Machop', 'ataque': 80', 'defensa': 50', 'vida': 70}
    machoke= {'nombre': 'Machoke', 'ataque': 100', 'defensa': 70', 'vida': 80}
    machamp= {'nombre': 'Machamp', 'ataque': 130', 'defensa': 80', 'vida': 90}
    bellsprout= {'nombre': 'Bellsprout', 'ataque': 75', 'defensa': 35', 'vida': 50}
    weepinbell= {'nombre': 'Weepinbell', 'ataque': 90', 'defensa': 50', 'vida': 65}
    victreebel= {'nombre': 'Victreebel', 'ataque': 105', 'defensa': 65', 'vida': 80}
    tentacool= {'nombre': 'Tentacool', 'ataque': 40', 'defensa': 35', 'vida': 40}
    tentacruel= {'nombre': 'Tentacruel', 'ataque': 70', 'defensa': 65', 'vida': 80}
    geodude= {'nombre': 'Geodude', 'ataque': 80', 'defensa': 100', 'vida': 40}
    geodude de alola= {'nombre': 'Geodude de Alola', 'ataque': 80', 'defensa': 100', 'vida': 40}
    graveler= {'nombre': 'Graveler', 'ataque': 95', 'defensa': 115', 'vida': 55}
    graveler de alola= {'nombre': 'Graveler de Alola', 'ataque': 95', 'defensa': 115', 'vida': 55}
    golem= {'nombre': 'Golem', 'ataque': 12014', 'defensa': 130', 'vida': 80}
    golem de alola= {'nombre': 'Golem de Alola', 'ataque': 120', 'defensa': 130', 'vida': 80}
]